//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beca
    {
        public int idbeca { get; set; }
        public string cedula { get; set; }
        public string idestudiante { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string cuenta_bancaria { get; set; }
        public string periodo { get; set; }
        public string tipo_beca { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
